import { Tag } from "lucide-react";
import {
  DynamicIcon,
  dynamicIconImports,
  type IconName,
} from "lucide-react/dynamic";
import { CATEGORY_ICONS } from "../../contracts/tag";

const iconSearchAliases: Record<string, string> = {
  AirVent: "空调 通风 空气",
  AlarmClock: "闹钟 提醒 时间",
  Apple: "水果 食物 餐饮 健康",
  AtSign: "邮箱 账号 提及",
  BadgeDollarSign: "钱 金额 财务 报销",
  BadgePercent: "折扣 优惠 百分比",
  Banknote: "现金 钱 金额 财务",
  Barcode: "条形码 商品 扫码",
  Bath: "洗浴 日用品 生活",
  Battery: "电池 电车 设备",
  BatteryCharging: "电池 充电 电车 设备",
  Bed: "住宿 睡眠 旅行 生活",
  Beef: "肉 食物 餐饮",
  Bike: "骑行 自行车 交通 运动",
  BookOpen: "书 学习 阅读 教育",
  Briefcase: "工作 办公 商务",
  Bus: "公交 交通 旅行 通勤",
  Cake: "蛋糕 甜点 食物",
  Calculator: "计算 财务 工具",
  Calendar: "日期 时间 日程",
  Camera: "相机 摄影 旅行 娱乐",
  Candy: "糖 零食 食物",
  Car: "汽车 交通 出行",
  CircleDollarSign: "钱 金额 财务",
  Cloud: "云服务 云 订阅 设备",
  Coffee: "咖啡 饮品 餐饮",
  Cookie: "饼干 零食 食物",
  CreditCard: "银行卡 支付 钱 财务",
  Cross: "医疗 健康 医院",
  Database: "数据库 云服务 设备",
  Dog: "宠物",
  Dumbbell: "健身 运动",
  EthernetPort: "网口 网络 设备",
  Fuel: "油费 汽车 交通",
  Gamepad2: "游戏 娱乐",
  Gift: "礼物 赠品",
  Globe: "全球 网络 互联网",
  GraduationCap: "学习 教育 课程",
  HandCoins: "钱 报销 财务",
  HardDrive: "硬盘 存储 设备",
  Headphones: "耳机 音频 设备",
  HeartPulse: "医疗 健康",
  Hospital: "医院 医疗 健康",
  Hotel: "酒店 住宿 旅行",
  House: "生活 住房 家",
  IceCream: "冰淇淋 零食 食物",
  Keyboard: "键盘 设备 数码",
  Laptop: "电脑 设备 数码",
  LibraryBig: "图书 学习",
  Mail: "邮件 邮箱 通知",
  MapPinned: "地图 地址 旅行",
  Monitor: "显示器 设备 数码",
  Music: "音乐 娱乐",
  Newspaper: "新闻 订阅 阅读",
  Package: "包裹 日用品 购物",
  PartyPopper: "娱乐 聚会",
  Percent: "百分比 折扣 优惠",
  Pill: "药 医疗 健康",
  Plane: "飞机 旅行 交通",
  Plug: "插头 电费 设备",
  Printer: "打印机 设备 办公",
  QrCode: "二维码 扫码 支付",
  Receipt: "账单 发票 小票",
  Refrigerator: "冰箱 家电 设备",
  Router: "网络 设备 云服务",
  Salad: "沙拉 食物 餐饮 健康",
  Sandwich: "三明治 食物 餐饮",
  Shirt: "衣服 服饰",
  ShoppingBag: "购物 消费",
  ShoppingCart: "购物 消费",
  Smartphone: "手机 设备 数码",
  Soup: "汤 食物 餐饮",
  Stethoscope: "医疗 健康",
  Ticket: "票 娱乐 旅行",
  Train: "火车 交通 旅行",
  TramFront: "电车 交通",
  Utensils: "餐饮 吃饭 三餐 食物",
  WashingMachine: "洗衣机 家电 设备",
  Wallet: "钱包 钱 财务",
  Wifi: "网络 云服务 设备",
  Wrench: "维修 工具 设备",
  Zap: "电 充电 电费",
};

const iconTokenAliases: Record<string, string> = {
  accessibility: "无障碍 辅助功能",
  activity: "活动 监测 状态",
  air: "空气 空调 通风",
  alarm: "闹钟 提醒 警报",
  align: "对齐 排版",
  ambulance: "救护车 急救 医疗",
  ampersand: "与 符号",
  anchor: "锚 固定 船",
  angry: "生气 表情",
  aperture: "光圈 摄影 相机",
  apple: "苹果 水果 食物",
  archive: "归档 存档",
  armchair: "椅子 家具",
  arrow: "箭头 方向",
  atom: "原子 科学",
  audio: "音频 声音",
  award: "奖项 荣誉",
  badge: "徽章 标识",
  bag: "包 购物",
  baggage: "行李 旅行",
  banana: "香蕉 水果 食物",
  banknote: "现金 钱 财务",
  barcode: "条形码 商品 扫码",
  bath: "洗浴 浴室",
  battery: "电池 电量 充电",
  beaker: "烧杯 实验",
  bean: "豆 食物",
  bed: "床 睡眠 住宿",
  beef: "肉 食物 餐饮",
  beer: "啤酒 饮品",
  bell: "铃声 通知 提醒",
  bike: "自行车 骑行 交通",
  binary: "二进制 代码",
  bitcoin: "比特币 加密货币",
  bluetooth: "蓝牙 设备",
  bold: "加粗 排版",
  bolt: "闪电 电",
  book: "书 学习 阅读",
  bookmark: "书签 收藏",
  bot: "机器人 AI 自动化",
  box: "盒子 包裹",
  brain: "大脑 智能 思考",
  briefcase: "公文包 工作 办公",
  brush: "画笔 绘画",
  bug: "错误 调试",
  building: "建筑 公司",
  bus: "公交 交通",
  cable: "线缆 连接",
  cake: "蛋糕 甜点",
  calculator: "计算器 财务",
  calendar: "日历 日期",
  camera: "相机 摄影",
  car: "汽车 交通",
  carrot: "胡萝卜 蔬菜 食物",
  chart: "图表 数据 统计",
  check: "勾选 完成",
  chef: "厨师 餐饮",
  cherry: "樱桃 水果 食物",
  chevron: "箭头 展开",
  circle: "圆形",
  clipboard: "剪贴板 清单",
  clock: "时钟 时间",
  cloud: "云服务 云端",
  code: "代码 编程",
  coffee: "咖啡 饮品",
  coin: "硬币 钱 财务",
  compass: "指南针 导航",
  computer: "电脑 设备",
  contact: "联系人",
  cookie: "饼干 零食",
  copy: "复制",
  copyright: "版权",
  corner: "角落 转向",
  cpu: "处理器 芯片 设备",
  credit: "信用卡 支付",
  croissant: "可颂 面包 食物",
  crop: "裁剪",
  cross: "十字 医疗",
  crown: "皇冠 会员",
  cup: "杯子 饮品",
  database: "数据库 数据",
  delete: "删除",
  diamond: "钻石 会员",
  dice: "骰子 游戏",
  disc: "光盘 存储",
  divide: "除法 计算",
  dna: "基因 生物 医疗",
  dollar: "美元 钱 财务",
  door: "门 出入口",
  download: "下载",
  droplet: "水滴 液体",
  dumbbell: "哑铃 健身 运动",
  earth: "地球 全球",
  egg: "鸡蛋 食物",
  equal: "等于 计算",
  eraser: "橡皮 擦除",
  ethernet: "网口 网络",
  euro: "欧元 钱 财务",
  expand: "展开 放大",
  external: "外部链接",
  eye: "眼睛 查看 可见",
  factory: "工厂 生产",
  fast: "快速",
  feather: "羽毛 写作",
  file: "文件 文档",
  film: "电影 视频",
  filter: "筛选 过滤",
  fingerprint: "指纹 安全",
  fire: "火 热门",
  fish: "鱼 食物",
  flag: "旗帜 标记",
  flame: "火 热门",
  flask: "烧瓶 实验",
  flower: "花 植物",
  folder: "文件夹",
  fork: "分支 餐具",
  frame: "框架 相框",
  frown: "难过 表情",
  fuel: "燃油 油费",
  gallery: "图库 相册",
  gamepad: "游戏 手柄 娱乐",
  gauge: "仪表盘 速度",
  gavel: "法槌 法律",
  gem: "宝石 会员",
  gift: "礼物 赠品",
  git: "代码 版本",
  globe: "全球 网络",
  goal: "目标",
  gps: "定位 导航",
  graduation: "毕业 学习 教育",
  grape: "葡萄 水果 食物",
  grid: "网格 布局",
  grip: "拖拽",
  group: "分组 团队",
  guitar: "吉他 音乐",
  hammer: "锤子 工具",
  hand: "手 操作",
  hard: "硬盘 存储",
  hash: "井号 标签",
  haze: "雾 天气",
  hdmi: "HDMI 接口",
  heading: "标题 排版",
  headphones: "耳机 音频",
  heart: "心 健康 喜欢",
  history: "历史 记录",
  hospital: "医院 医疗",
  hotel: "酒店 住宿",
  house: "房子 家 生活",
  image: "图片 图像",
  inbox: "收件箱",
  indent: "缩进 排版",
  infinity: "无限",
  info: "信息",
  inspection: "检查",
  instagram: "社交 媒体",
  italic: "斜体 排版",
  joystick: "游戏 摇杆",
  key: "钥匙 密码 安全",
  keyboard: "键盘 设备",
  lamp: "灯 照明",
  landmark: "地标 银行",
  language: "语言 翻译",
  laptop: "笔记本 电脑",
  lasso: "套索 选择",
  laugh: "笑 表情",
  layers: "图层 层级",
  layout: "布局",
  leaf: "叶子 环保",
  library: "图书馆 学习",
  life: "生命 救援",
  lightbulb: "灯泡 灵感",
  link: "链接",
  list: "列表 清单",
  loader: "加载",
  lock: "锁 安全",
  log: "日志 登录",
  luggage: "行李 旅行",
  magnet: "磁铁 吸附",
  mail: "邮件 邮箱",
  map: "地图 导航",
  medal: "奖牌 荣誉",
  megaphone: "喇叭 公告",
  memory: "内存 设备",
  menu: "菜单",
  message: "消息 聊天",
  mic: "麦克风 录音",
  microwave: "微波炉 家电",
  milestone: "里程碑",
  milk: "牛奶 饮品",
  minus: "减号 删除",
  monitor: "显示器 设备",
  moon: "月亮 夜晚",
  mountain: "山 旅行",
  mouse: "鼠标 设备",
  move: "移动",
  music: "音乐 娱乐",
  navigation: "导航 方向",
  network: "网络",
  newspaper: "新闻 阅读",
  notebook: "笔记本 笔记",
  octagon: "八边形 停止",
  orbit: "轨道",
  package: "包裹 日用品",
  paint: "绘画 颜色",
  panel: "面板",
  parking: "停车 交通",
  party: "派对 娱乐",
  pause: "暂停",
  pen: "钢笔 书写",
  pencil: "铅笔 编辑",
  percent: "百分比 折扣",
  phone: "电话 手机",
  piano: "钢琴 音乐",
  picture: "图片",
  pie: "饼图 数据",
  piggy: "存钱 储蓄",
  pill: "药 医疗",
  pin: "固定 图钉",
  pipette: "吸管 取色",
  pizza: "披萨 食物",
  plane: "飞机 旅行",
  plug: "插头 电源",
  plus: "加号 新增",
  pointer: "指针 点击",
  popcorn: "爆米花 电影 零食",
  power: "电源 开关",
  printer: "打印机 办公",
  projector: "投影仪 设备",
  qr: "二维码 扫码",
  radio: "广播 音频",
  receipt: "票据 发票 账单",
  recycle: "回收 环保",
  redo: "重做",
  refresh: "刷新",
  refrigerator: "冰箱 家电",
  repeat: "重复 循环",
  reply: "回复",
  rewind: "倒退",
  ribbon: "丝带 奖励",
  rocket: "火箭 启动",
  route: "路线 导航",
  router: "路由器 网络",
  rss: "订阅",
  ruler: "尺子 测量",
  salad: "沙拉 餐饮",
  save: "保存",
  scale: "秤 比例",
  scan: "扫描",
  school: "学校 学习",
  scissors: "剪刀 工具",
  search: "搜索",
  send: "发送",
  server: "服务器 设备",
  settings: "设置",
  share: "分享",
  shield: "盾牌 安全",
  ship: "船 交通 旅行",
  shirt: "衣服 服饰",
  shopping: "购物 消费",
  shower: "淋浴 洗浴",
  shrink: "收起 缩小",
  shuffle: "随机",
  signal: "信号 网络",
  signature: "签名",
  slash: "斜杠 禁用",
  sliders: "滑杆 设置",
  smartphone: "手机 设备",
  smile: "笑 表情",
  sofa: "沙发 家具",
  soup: "汤 餐饮",
  speaker: "音箱 音频",
  speech: "语音 聊天",
  square: "方形",
  star: "星标 收藏",
  sticker: "贴纸",
  stopwatch: "秒表 时间",
  store: "商店 购物",
  suitcase: "行李箱 旅行",
  sun: "太阳 白天",
  sunrise: "日出",
  sunset: "日落",
  table: "表格",
  tablet: "平板 设备",
  tag: "标签 分类",
  target: "目标",
  telescope: "望远镜 科学",
  tent: "帐篷 露营",
  terminal: "终端 命令行",
  text: "文字 文本",
  thermometer: "温度计 天气",
  thumbs: "点赞",
  ticket: "票券 娱乐",
  timer: "计时器 时间",
  toggle: "开关",
  toilet: "厕所 卫生间",
  traffic: "交通 红绿灯",
  train: "火车 交通",
  tram: "电车 交通",
  trash: "垃圾 删除",
  tree: "树 植物",
  trending: "趋势",
  triangle: "三角形",
  trophy: "奖杯 荣誉",
  truck: "卡车 物流",
  tv: "电视 设备",
  type: "文字 输入",
  umbrella: "雨伞 天气",
  underline: "下划线 排版",
  undo: "撤销",
  university: "大学 学校",
  unlink: "取消链接",
  upload: "上传",
  usb: "USB 接口",
  user: "用户 个人",
  utensils: "餐具 餐饮 三餐",
  vegan: "素食 餐饮",
  video: "视频 摄像",
  voicemail: "语音信箱",
  volume: "音量 声音",
  vote: "投票",
  wallet: "钱包 支付",
  wallpaper: "壁纸 图片",
  wand: "魔棒 AI",
  warehouse: "仓库 库存",
  washing: "洗衣机 清洁 家电",
  watch: "手表 时间",
  waves: "波浪 水",
  webcam: "摄像头 设备",
  webhook: "接口 回调",
  wheat: "小麦 食物",
  wifi: "无线 网络",
  wind: "风 天气",
  wine: "酒 饮品",
  wrench: "扳手 维修 工具",
  youtube: "视频 媒体",
  zap: "闪电 电 充电",
  zoom: "缩放",
};

const iconImportMap = dynamicIconImports as unknown as Record<string, unknown>;

function kebabToPascal(name: string) {
  return name
    .split("-")
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function pascalToKebab(name: string) {
  return name
    .replace(/([A-Z])([A-Z][a-z])/g, "$1-$2")
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/([a-zA-Z])([0-9])/g, "$1-$2")
    .toLowerCase();
}

function splitPascalWords(name: string) {
  return name
    .replace(/([A-Z])([A-Z][a-z])/g, "$1 $2")
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .replace(/([a-zA-Z])([0-9])/g, "$1 $2")
    .trim()
    .split(/\s+/)
    .filter(Boolean);
}

function uniqueTerms(terms: string[]) {
  return Array.from(
    new Set(
      terms
        .flatMap(term => term.split(/\s+/))
        .map(term => term.trim())
        .filter(Boolean)
    )
  );
}

function buildChineseKeywords(name: string) {
  const tokenAliases = splitPascalWords(name).flatMap(
    token => iconTokenAliases[token.toLowerCase()]?.split(/\s+/) ?? []
  );

  return uniqueTerms([
    ...(iconSearchAliases[name]?.split(/\s+/) ?? []),
    ...tokenAliases,
  ]);
}

function getIconKey(name?: string | null): IconName {
  const iconKey = pascalToKebab(name || "Tag");
  return (iconImportMap[iconKey] ? iconKey : "tag") as IconName;
}

const allIconNames = Array.from(
  new Set(Object.keys(iconImportMap).map(kebabToPascal))
).sort();
const prioritizedIconNames = [
  ...CATEGORY_ICONS,
  ...allIconNames.filter(name => !CATEGORY_ICONS.includes(name as never)),
];

export const CATEGORY_ICON_OPTIONS = prioritizedIconNames.map(name => ({
  name,
  keywords: buildChineseKeywords(name).slice(0, 8).join(" "),
  searchText: uniqueTerms([
    name,
    splitPascalWords(name).join(" "),
    ...buildChineseKeywords(name),
  ]).join(" "),
}));

export function CategoryIcon({
  name,
  className,
}: {
  name?: string | null;
  className?: string;
}) {
  return (
    <DynamicIcon
      name={getIconKey(name)}
      className={className}
      fallback={() => <Tag className={className} />}
    />
  );
}
